version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "15432:5432"
    volumes:
      # - db_data:/var/lib/postgresql/data
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    command: [
      "postgres",
      "-c", "max_pred_locks_per_transaction=256",
      "-c", "max_pred_locks_per_relation=64",
      "-c", "max_pred_locks_per_page=8",
      "-c", "log_statement=all",
      "-c", "log_min_messages=debug1",
      "-c", "debug_print_parse=on",
      "-c", "debug_print_rewritten=on",
      "-c", "debug_print_plan=on"
    ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
